AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Include:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - '**/*.rake'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
